const bool success := true;


print(success);


//var int a;
//var int b;
//var int c;
//var int d;
//var bool k;
//var char x;
//read(d,x,a,d);
//print(d,x);
//
//b:=read(a);
//read(c,d);
//
//print(a+b,c+d);
//read(a,k,x);
//print(a,k,x);

//print(!true)
//
//print('a');
//
//print('a' <> 'a'); // false
//print('a' == 'a'); // true
//
//var int a;
//var int b;
//var int c;
//var int d;
//
//b := c := 5;
//a := 3;
//d := 7;
//
//5+6;
//
//print(true || false); // true
//print(true && true); // true
//print(true && false); // false
//print(true && (false || true)); // true
//
//print(true);
//print(false);
//
//print(a); // 3
//
//print(b == c); //True
//print(b <> c); //False
//print(b <  c); //False
//print(b >  c); //False
//print(b <= c); //True
//print(b >= c); //True
//
//
//print(a == b); //False
//print(a <> b); //True
//print(a <  b); //True
//print(a >  b); //False
//print(a <= b); //True
//print(a >= b); //False
//
//print(d == c); //False
//print(d <> c); //True
//print(d <  c); //False
//print(d >  c); //True
//print(d <= c); //False
//print(d >= c); //True
//
//print(8,9);
